### ISSUE TITLE
"Bug Status" graph

### ISSUE THREAD

**Issue by simson-suse** [openSUSE/nailed#47]
Similar to the current "Bug Priorities".

Requested by: aojeagarcia

**Comment by aojea** [comment]
We have a graph that shows the number of bugs per priority.

![image](https://user-images.githubusercontent.com/6450081/39363825-f5e1f622-4a2b-11e8-8edd-57147227e5f0.png)


I think it could be useful to have the same graph, but aggregating the bugs per [status](https://bugzilla.suse.com/page.cgi?id=status_resolution_matrix.html), I mean using the bug status (NEW,CONFIRMED, ...) in the X axis instead of the Priority level.

**Comment by simson-suse** [comment]
Pushed to the live system ;-)
